# Notebook pour l'école d'été LivreQuanti2023

# Environnement

In [ ]:
!conda info

In [1]:
import os
print(os.getcwd())

C:\Users\stutzmann\Github\LivreQuanti2023\DataModelling

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly
import plotly.express as px
import plotly.io as pio
from plotly.subplots import make_subplots
import plotly.graph_objects as go

print("pd : ", pd.__version__)
print("np : ", np.__version__)
print("sns : ", sns.__version__)
print("plotly : ", plotly.__version__)
plt.close("all")

pd :  2.0.1
np :  1.24.3
sns :  0.11.2
plotly :  4.14.3

# Données

In [3]:
mss = pd.read_csv("Export_stutzmann_horae_t53_Manuscript.csv", encoding="UTF-8", sep=",")

## Vérifier le chargement des données

In [10]:
mss.shape

(1250, 38)

In [11]:
mss.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1250 entries, 0 to 1249
Data columns (total 38 columns):
 #   Column                                                       Non-Null Count  Dtype
---  ------                                                       --------------  -----
 0   Manuscript H-ID                                              1250 non-null   int64
 1   repository_key (Organisation) H-ID                           1250 non-null   int64
 2   rec_Title                                                    1250 non-null   object
 3   repository_key (Organisation) Record Title                   1250 non-null   object
 4   rec_Title.1                                                  1250 non-null   object
 5   idno                                                         1250 non-null   object
 6   altIdentifier                                                85 non-null     object
 7   idMedium                                                     713 non-null    object
 8   number of volume                                             51 non-null     float64
 9   support                                                      795 non-null    object
 10  extent                                                       1130 non-null   object
 11  leaf dimensions : height (mm)                                1074 non-null   object
 12  leaf dimensions : width (mm)                                 1070 non-null   object
 13  justification : height (mm)                                  250 non-null    object
 14  justification : width (mm)                                   250 non-null    object
 15  columns                                                      898 non-null    float64
 16  writtenLines                                                 534 non-null    float64
 17  writtenLines (notes)                                         11 non-null     float64
 18  writtenLines (note)                                          115 non-null    float64
 19  script type                                                  587 non-null    object
 20  formality                                                    430 non-null    object
 21  handNote                                                     40 non-null     object
 22  scriptNote                                                   78 non-null     object
 23  note (deco)                                                  513 non-null    object
 24  origDate                                                     50 non-null     object
 25  origDate : from                                              1128 non-null   object
 26  origDate : to                                                1126 non-null   object
 27  origDate : proposed date                                     871 non-null    object
 28  origPlace (relationship marker) (Organisation) H-ID          0 non-null      float64
 29  rec_Title.2                                                  0 non-null      float64
 30  origPlace (relationship marker) (Organisation) Record Title  679 non-null    object
 31  rec_Title.3                                                  0 non-null      float64
 32  origPlace (relationship marker) H-ID                         679 non-null    object
 33  rec_Title.4                                                  573 non-null    object
 34  origPlace (relationship marker) Record Title                 91 non-null     object
 35  rec_Title.5                                                  79 non-null     object
 36  origPlace : proposed origin                                  1250 non-null   object
 37  iiif manifest                                                0 non-null      float64
dtypes: float64(9), int64(2), object(27)
memory usage: 371.2+ KB

In [4]:
mss.head()

,Manuscript H-ID,repository_key (Organisation) H-ID,rec_Title,repository_key (Organisation) Record Title,rec_Title.1,idno,altIdentifier,idMedium,number of volume,support,...,origPlace (relationship marker) (Organisation) H-ID,rec_Title.2,origPlace (relationship marker) (Organisation) Record Title,rec_Title.3,origPlace (relationship marker) H-ID,rec_Title.4,origPlace (relationship marker) Record Title,rec_Title.5,origPlace : proposed origin,iiif manifest
0,14,740110,"Innsbruck, Universitätsbibliothek (Organisation)","Innsbruck, Universitätsbibliothek (Organisation)",rec_Title,281,NaN,NaN,NaN,NaN,...,NaN,NaN,38032,NaN,Tours (Place),rec_Title,NaN,NaN,https://diglib.uibk.ac.at/i3f/v20/5921243/mani...,NaN
1,163,739655,"Brugge, Openbare Bibliotheek Brugge (Biekorf) ...","Brugge, Openbare Bibliotheek Brugge (Biekorf) ...",rec_Title,Ms. 321,NaN,3858,NaN,parchment,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://sharedcanvas.be/IIIF/manifests/B_OB_SV...,NaN
2,164,739655,"Brugge, Openbare Bibliotheek Brugge (Biekorf) ...","Brugge, Openbare Bibliotheek Brugge (Biekorf) ...",rec_Title,Ms. 329,NaN,100056147,NaN,parchment,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://sharedcanvas.be/IIIF/manifests/B_OB_MS329,NaN
3,349,739678,"Gent, Universiteitsbibliotheek (Organisation)","Gent, Universiteitsbibliotheek (Organisation)",rec_Title,186,NaN,NaN,NaN,parchment,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://adore.ugent.be/IIIF/manifests/archive....,NaN
4,350,739678,"Gent, Universiteitsbibliotheek (Organisation)","Gent, Universiteitsbibliotheek (Organisation)",rec_Title,197,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://adore.ugent.be/IIIF/manifests/archive....,NaN

# Créer du bruit

In [53]:
import nltk
nltk.download('omw-1.4')
nltk.download('wordnet')
from nltk.corpus import wordnet
import random

[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\stutzmann\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\stutzmann\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

## Exemples de code de Chat-GPT

In [55]:
# Example DataFrame
df = pd.DataFrame({'Text1': ['This is a sentence.', 'Another example.', 'Text data.', 'Some text.'],
                   'Text2': ['Hello world!', 'Python programming.', 'Data analysis.', 'Machine learning.']})

# Columns to add noise
columns_with_noise = ['Text1', 'Text2']

# Add noise to selected columns
for column in columns_with_noise:
    # Iterate over each row in the column
    for i in range(len(df)):
        # Split the text into individual words
        words = df.loc[i, column].split()
        
        # Add noise to each word
        noisy_words = []
        for word in words:
            # Randomly choose a noise operation (e.g., adding random word or shuffling characters)
            noise_operation = random.choice(['add_word', 'shuffle_chars'])
            
            # Apply the noise operation
            if noise_operation == 'add_word':
                # Add a random word from the WordNet corpus
                synsets = wordnet.synsets(word)
                if synsets:
                    random_synset = random.choice(synsets)
                    random_word = random_synset.lemmas()[0].name()
                    noisy_words.append(random_word.replace('_', ' '))
            elif noise_operation == 'shuffle_chars':
                # Shuffle the characters within the word
                shuffled_word = ''.join(random.sample(word, len(word)))
                noisy_words.append(shuffled_word)
        
        # Join the noisy words back into a sentence
        noisy_text = ' '.join(noisy_words)
        
        # Update the DataFrame with the noisy text
        df.loc[i, column] = noisy_text

# Display the updated DataFrame
print(df)

              Text1                Text2
0    is a .enntecse                hello
1  tnhroAe eex.lpam  python npaomgmrir.g
2              txeT       aatD lnia.sysa
3        some x.tet    machine earng.nil

In [56]:
# Example DataFrame
df = pd.DataFrame({'Text1': ['This is a sentence.', 'Another example.', 'Text data.', 'Some text.'],
                   'Text2': ['Hello world!', 'Python programming.', 'Data analysis.', 'Machine learning.']})

# Columns to add noise
columns_with_noise = ['Text1', 'Text2']

# Function to introduce spelling mistakes in a word
def introduce_spelling_mistake(word):
    # Randomly choose a mistake operation (e.g., replacing character, adding or removing character)
    mistake_operation = random.choice(['replace', 'add', 'remove'])

    if mistake_operation == 'replace':
        # Replace a character with a similar-looking character
        letters = list(word)
        index = random.randint(0, len(letters) - 1)
        letters[index] = random.choice(list(letters[index]))
        return ''.join(letters)
    elif mistake_operation == 'add':
        # Add a random character after a randomly chosen position
        letters = list(word)
        index = random.randint(0, len(letters))
        letters.insert(index, random.choice(list('abcdefghijklmnopqrstuvwxyz')))
        return ''.join(letters)
    elif mistake_operation == 'remove':
        # Remove a character at a randomly chosen position
        letters = list(word)
        index = random.randint(0, len(letters) - 1)
        del letters[index]
        return ''.join(letters)
    else:
        return word

# Add noise to selected columns
for column in columns_with_noise:
    # Iterate over each row in the column
    for i in range(len(df)):
        # Split the text into individual words
        words = df.loc[i, column].split()
        
        # Add noise to each word
        noisy_words = []
        for word in words:
            # Apply spelling mistake only if the word has more than two characters
            if len(word) > 2:
                # Randomly choose whether to introduce a spelling mistake or not
                introduce_mistake = random.random() < 0.5  # Adjust the probability as per your requirement
                
                if introduce_mistake:
                    # Introduce a spelling mistake
                    noisy_word = introduce_spelling_mistake(word)
                    noisy_words.append(noisy_word)
                else:
                    noisy_words.append(word)
            else:
                noisy_words.append(word)
        
        # Join the noisy words back into a sentence
        noisy_text = ' '.join(noisy_words)
        
        # Update the DataFrame with the noisy text
        df.loc[i, column] = noisy_text

# Display the updated DataFrame
print(df)

                Text1                Text2
0  Thi is a sentence.        kHello world!
1    Aother exzample.  Pythoan programmig.
2          Text data.      Data analysdis.
3          Some text.    Machine learning.

In [57]:
# Example DataFrame
df = pd.DataFrame({'Text1': ['This is a sentence.', 'Another example.', 'Text data.', 'Some text.'],
                   'Text2': ['Hello world!', 'Python programming.', 'Data analysis.', 'Machine learning.']})

# Columns to add noise
columns_with_noise = ['Text1', 'Text2']

# Function to introduce spelling mistakes in a word
def introduce_spelling_mistake(word):
    # Randomly choose a mistake operation (e.g., replacing character, adding or removing character)
    mistake_operation = random.choice(['replace', 'add', 'remove'])

    if mistake_operation == 'replace':
        # Replace a character with a similar-looking character
        letters = list(word)
        index = random.randint(0, len(letters) - 1)
        letters[index] = random.choice(list(letters[index]))
        return ''.join(letters)
    elif mistake_operation == 'add':
        # Add a random character after a randomly chosen position
        letters = list(word)
        index = random.randint(0, len(letters))
        letters.insert(index, random.choice(list('abcdefghijklmnopqrstuvwxyz')))
        return ''.join(letters)
    elif mistake_operation == 'remove':
        # Remove a character at a randomly chosen position
        letters = list(word)
        index = random.randint(0, len(letters) - 1)
        del letters[index]
        return ''.join(letters)
    else:
        return word

# Add noise to selected columns
for column in columns_with_noise:
    # Iterate over each row in the column
    for i in range(len(df)):
        # Split the text into individual words
        words = df.loc[i, column].split()
        
        # Add noise to each word
        noisy_words = []
        for word in words:
            # Apply spelling mistake only if the word has more than two characters
            if len(word) > 2:
                # Randomly choose whether to introduce a spelling mistake or not
                introduce_mistake = random.random() < 0.5  # Adjust the probability as per your requirement
                
                if introduce_mistake:
                    # Introduce a spelling mistake
                    word = introduce_spelling_mistake(word)
            
            noisy_words.append(word)
        
        # Join the noisy words back into a sentence
        noisy_text = ' '.join(noisy_words)
        
        # Update the DataFrame with the noisy text
        df.loc[i, column] = noisy_text

# Display the updated DataFrame
print(df)

                 Text1                 Text2
0  This is a sentence.          Hello world!
1    Another exxample.  Python programming.o
2            Text daa.        Data analysis.
3           rSome text     Machine learning.

## Adaptation à HORAE

In [33]:
df = mss.copy(deep=True)

In [16]:
columns_with_noise = ['writtenLines']

# Add noise to selected columns
noise_scale = 0.1  # Adjust the noise scale as per your requirements
df[columns_with_noise] += np.random.normal(loc=0, scale=noise_scale, size=(len(df), len(columns_with_noise)))

In [23]:
mss['writtenLines'].unique()

array([nan, 15., 20., 18., 14., 24., 12., 13., 17., 16., 19., 33., 21.,
       10., 31., 23., 11., 26., 22., 27., 28., 32., 30., 29., 25.,  7.])

In [20]:
df['writtenLines'].unique()

array([        nan, 14.89336393, 20.09881747, 17.93383572, 14.18434903,
       23.93698569, 14.06015729, 23.97211892, 18.02810343, 11.84496   ,
       12.93069175, 17.08733269, 15.91133806, 18.83334623, 15.07800801,
       33.04647854, 14.10481598, 19.00232776, 13.04022212, 20.01520407,
       15.04512814, 13.06021981, 13.93465548, 15.11210555, 21.02476866,
       16.05883815, 16.17735443, 15.88905711, 16.84832437, 16.93496684,
       17.0644034 , 14.79355378, 19.00665059, 17.07942569, 18.9293648 ,
       16.93451615, 13.99534522, 14.83224236, 18.11798609,  9.98545579,
       18.0824269 , 14.85386479, 20.9360122 , 15.82573473, 31.07379502,
       14.03253725, 13.98388182, 17.08182791, 12.99896562, 15.90282433,
       13.96445392, 14.87972737, 17.94943587, 17.83164882, 21.04278711,
       15.86781426, 20.01373881, 11.91460285, 14.97127994, 14.93447052,
       16.98227486, 14.9815356 , 23.08731391, 17.04099193, 11.13501333,
       16.03229497, 13.02626801, 14.99944371, 21.09801438, 13.14218481,
       14.91515598, 18.10431219, 17.85178358, 13.98139382,  9.97644672,
       23.81079334, 16.98747129, 15.01575506, 26.02134796, 15.08693571,
       11.184716  , 14.16479991, 15.91697827, 17.83806644, 16.12202601,
       15.09785138, 18.02170621,  9.83891276, 13.95593664, 21.90573879,
       17.03317513, 14.98205616, 12.93130286, 11.97236058, 14.04854616,
       15.06703705, 17.98988753, 19.97432087, 21.81036873, 14.98000345,
       22.02666426, 21.02170872, 13.91389459, 11.99910801, 20.89620185,
       15.9948522 , 22.02472243, 16.92102099, 15.91944724, 16.0770134 ,
       19.91270477, 16.02766047, 18.09442153, 13.94086345, 14.94871313,
       19.11981686, 26.85568198, 12.03683589, 15.01014259, 16.07613008,
       17.15898971, 15.00252529, 18.02760374, 15.09859589, 16.01573607,
       13.98557766, 14.10879132, 13.9989121 , 21.10877188, 20.04475615,
       16.74447467, 14.96484872, 15.99051115, 12.04329025, 16.90427175,
       23.92168068, 20.14947642, 14.01310821, 16.99450018, 11.90703365,
       12.91546488, 12.97069498, 15.00069087, 16.02077652, 18.11816885,
       13.95411777, 15.06477927, 16.07641513, 15.97826353, 16.00817528,
       19.90587854, 20.07722027, 16.00593297, 12.99489524, 17.9788939 ,
       16.11606921, 13.98839463, 13.97992619, 14.94693788, 13.03690552,
       15.09086711, 20.92075251, 19.97261842, 16.07281537, 23.00718866,
       17.88972995, 17.02539782, 16.88974153, 16.8721032 , 25.90712115,
       19.81162846, 15.03899375, 16.03615123, 17.96851922, 15.93210732,
       25.95612224, 15.91130581, 18.12361781, 28.09588913, 11.86621494,
       32.05219985, 12.98053611, 17.02415366, 21.96617251, 21.87381175,
       18.82381138, 27.99993341, 14.04827483, 29.8663415 , 14.96138924,
       30.06595962, 15.93763686, 14.08019487, 15.10067017, 16.96974309,
       18.99328089, 13.83412151, 18.92637555, 12.88504116, 17.02796725,
       31.09843102, 17.10592481, 29.09579344, 15.99611032, 15.0430668 ,
       16.04747851, 15.83689981, 15.98955413, 19.98520874, 13.99587625,
       12.00783308, 17.87535004, 16.06909297, 20.00455519, 16.03871619,
       17.98824516,  9.90617834, 27.0072333 , 14.78220428, 16.10724411,
       14.9785361 , 19.1259582 , 16.83459608, 17.07410788, 13.90922027,
       22.91565875, 20.04778321, 21.8738207 , 17.12956882, 21.13556222,
       17.89544954, 24.07095725, 20.02327283, 15.87951254, 31.08894296,
       23.97906425, 27.16354977, 16.05636196, 14.99048864, 13.05594791,
       18.14725863, 15.13131452, 21.8920659 , 16.19463795, 25.02224822,
       17.04713966, 21.97810703, 20.94251579, 19.99615891, 14.99102429,
       17.85811486, 16.90131549, 23.95643089, 14.91467301, 23.82496316,
       14.12773337, 16.04671838, 17.84873081, 18.96281547, 22.05074504,
       16.92183209, 15.11259128, 17.00816096, 15.01410903, 19.86102964,
       22.12997476, 15.95192997, 14.08111682, 14.86355265, 17.03057596,
       14.97229967, 17.99615433, 23.87115325, 15.87830531, 14.02171489,
       15.96855472, 17.97293755, 21.01499982, 14.87478786, 14.98807394,
       14.89305126, 15.90799398, 14.08528464, 13.85601025, 13.9688521 ,
       18.04844385, 15.99136139, 16.9122458 , 20.19901458, 15.89935172,
       15.08651689, 14.83451489, 23.94916044, 27.99269847, 17.97451256,
       14.97808796, 15.71832962, 18.03676079, 14.00480999, 13.93427031,
       13.9693639 , 13.98442703, 12.94969224, 14.94923485, 16.87344075,
       15.92843775, 17.10558799, 28.05055185, 14.05828116, 14.06365956,
       16.0284208 , 18.15362871, 15.97184251, 13.93144297, 19.04778644,
       16.00480204, 16.15854331, 18.04511205, 15.14252544, 13.07058684,
       17.84957375, 19.00966155, 13.92415364, 16.16845514, 13.92929318,
       13.95690299, 20.89112886, 15.06138576, 15.88806184, 13.95840506,
       15.93569239, 14.20399587, 15.11328589, 13.92067995, 19.10916887,
       16.9445635 , 18.08252042, 17.86520103, 15.15137014, 17.10981838,
       15.08751604, 15.01447191, 14.11183901, 14.00853586, 13.93518206,
       15.02028831, 12.97381739, 16.03966561, 15.96339536, 12.94344523,
       18.9341407 , 15.10231353, 15.12435115, 15.92935099, 21.9508203 ,
       14.9858133 , 14.96762888, 16.96263201, 15.06495364, 12.07619827,
       12.10788679, 14.9423018 , 15.98236714, 32.06255458, 19.05091341,
       15.74942855, 17.06844446, 15.94158591, 14.05442946, 24.02802545,
       16.07474204, 17.04179806, 16.08144433, 14.05367917, 12.9889605 ,
       13.80695115, 18.03112116, 12.04360061, 14.9918432 , 15.00996297,
       10.95681467, 22.06875192, 13.09377683, 13.9142623 , 18.99796025,
       11.97345629, 16.91558521, 18.19727227, 17.99385897, 17.16934601,
       20.09866834, 13.91414905, 17.89445399, 18.97633475, 16.85521258,
       19.03258459, 17.10164753, 14.87954892, 15.03710297, 14.8878324 ,
       16.09906427, 11.90790092, 18.12937572, 21.08079542, 23.12513304,
       25.8858294 , 25.08288253, 24.90306791, 13.97569344, 16.99781917,
       15.02117804, 17.82635049, 27.03798547, 14.97056592, 30.92685992,
       15.00694514, 14.01722898, 15.16183721, 11.01387791, 13.09532825,
       31.01559342, 21.993774  , 13.16591427, 14.98856653, 16.98973317,
       19.96849089, 20.07865716, 14.96278883, 14.91767567, 12.95790185,
       15.21936873, 14.020964  , 20.10032566, 15.98545243, 16.89707018,
       15.15761927,  7.07761278, 15.79831477, 14.94926335, 16.12363648,
       15.7513506 , 14.91335932, 27.99055305, 15.02183552, 21.92764152,
       14.00689717, 20.8343695 , 26.7615919 , 17.97965975, 21.14649855,
       15.97030341, 18.94985649, 18.04596277, 12.99803939, 15.11147265,
       15.01331822, 16.87148007, 13.91443829, 18.07599736, 18.1836868 ,
       14.08402145, 22.0734171 , 18.01154277, 26.10134573, 25.77102825,
       22.16977976, 18.76867417, 32.97623811, 15.8312949 , 14.96763416,
       14.99711343, 17.97036043, 14.09767906, 13.94643448, 18.96087291,
       24.92666013, 17.6386504 , 18.99782537, 22.11083529, 15.973395  ,
       17.9318422 , 17.10041014, 17.06690812, 11.02688741, 17.85589409,
       16.17500808, 13.95272221, 20.0281993 , 22.04322446, 17.06993566,
       12.88408988, 15.13493047, 19.94164174, 25.05829516, 13.87297562,
       18.08034237, 15.15651481, 19.83432697, 18.8422929 , 19.02514939,
       18.03885712, 19.9857322 , 20.88164323, 20.87273419, 22.03871454,
       32.09558437, 18.8824445 , 16.98601606, 14.0813877 , 13.98495205,
       15.10863539, 13.89139824, 18.13321271, 12.05688584, 16.0291413 ,
       18.84487218, 21.05664599, 13.93750393, 20.04981042, 15.17751061,
       14.97642209, 12.96893158, 15.93702903, 13.78515223, 15.9708057 ,
       19.90402221, 21.93556829, 13.8392213 , 16.9956438 , 16.26797185,
       20.98019789, 15.11123411, 17.11359658, 22.06521318, 15.18713192])

In [34]:
# Columns to add noise
columns_with_noise = ['repository_key (Organisation) Record Title']

# Add noise to selected columns
for column in columns_with_noise:
    # Iterate over each row in the column
    for i in range(len(df)):
        # Split the text into individual words
        words = df.loc[i, column].split()
        
        # Add noise to each word
        noisy_words = []
        for word in words:
            # Randomly choose a noise operation (e.g., adding random word or shuffling characters)
            # noise_operation = random.choice(['add_word', 'shuffle_chars'])
            noise_operation = random.choice(['shuffle_chars'])
            
            # Apply the noise operation
            if noise_operation == 'add_word':
                # Add a random word from the WordNet corpus
                synsets = wordnet.synsets(word)
                if synsets:
                    random_synset = random.choice(synsets)
                    random_word = random_synset.lemmas()[0].name()
                    noisy_words.append(random_word.replace('_', ' '))
            elif noise_operation == 'shuffle_chars':
                # Shuffle the characters within the word
                shuffled_word = ''.join(random.sample(word, len(word)))
                noisy_words.append(shuffled_word)
        
        # Join the noisy words back into a sentence
        noisy_text = ' '.join(noisy_words)
        
        # Update the DataFrame with the noisy text
        df.loc[i, column] = noisy_text

In [30]:
mss['repository_key (Organisation) Record Title'].unique()

array(['Innsbruck, Universitätsbibliothek (Organisation)',
       'Brugge, Openbare Bibliotheek Brugge (Biekorf) (Organisation)',
       'Gent, Universiteitsbibliotheek (Organisation)',
       'Tournai, Bibliothèque du Séminaire (Organisation)',
       'Vancouver, University of British Columbia Library (Organisation)',
       'Basel, Universitätsbibliothek (Organisation)',
       'Chavannes-près-Renens, Archives cantonales vaudoises (Organisation)',
       'Genève, Bibliothèque de Genève (Organisation)',
       'Hermetschwil, Benediktinerinnenkloster (Organisation)',
       'Luzern, Zentral- und Hochschulbibliothek (Organisation)',
       'Neuchâtel, Bibliothèque publique et universitaire de Neuchâtel (Organisation)',
       'Porrentruy, Bibliothèque cantonale jurassienne (Organisation)',
       'Sarnen, Benediktinerkollegium (Organisation)',
       'St. Gallen, Stiftsbibliothek (Organisation)',
       'Trogen, Kantonsbibliothek Appenzell Ausserrhoden (Organisation)',
       'Utopia, Armarium codicum bibliophilorum (Organisation)',
       'Zürich, Schweizerisches Nationalmuseum (Organisation)',
       'Zürich, Zentralbibliothek (Organisation)',
       'Praha, Klášter premonstrátů na Strahově (Organisation)',
       'Praha, Knihovna Národního muzea (Organisation)',
       'Fulda, Hochschul- und Landesbibliothek (Organisation)',
       'Karlsruhe, Badische Landesbibliothek (Organisation)',
       'München, Bayerische Staatsbibliothek (Organisation)',
       'Madrid, Biblioteca Nacional de España (Organisation)',
       'Madrid, Real Biblioteca (Organisation)',
       'Abbeville, Bibliothèque municipale (Organisation)',
       'Albi, Bibliothèque municipale (Organisation)',
       'Alençon, Bibliothèque municipale (Organisation)',
       'Ambierle, Musée Alice Taverne (Organisation)',
       'Angers, Bibliothèque municipale (Organisation)',
       'Angers, Musée des Beaux-Arts (Organisation)',
       'Annecy, Bibliothèque municipale (Organisation)',
       'Apt, Musée Trésor de la Cathédrale Sainte-Anne (Organisation)',
       'Argentan, Bibliothèque municipale (Organisation)',
       'Arras, Bibliothèque municipale (Organisation)',
       'Arras, Musée diocésain (Organisation)',
       'Auch, Bibliothèque municipale (Organisation)',
       'Autun, Bibliothèque de la Société Eduenne (Organisation)',
       'Autun, Bibliothèque municipale (Organisation)',
       'Autun, Musée Rolin (Organisation)',
       'Auxerre, Trésor de la cathédrale (Organisation)',
       'Avranches, Bibliothèque municipale (Organisation)',
       'Bayeux, Bibliothèque du chapitre (Organisation)',
       'Bayeux, Bibliothèque municipale (Organisation)',
       'Beaune, Archives hospitalières (Organisation)',
       'Beaune, Bibliothèque municipale (Organisation)',
       'Bergues, Bibliothèque municipale (Organisation)',
       'Besançon, Bibliothèque municipale (Organisation)',
       'Blois, Bibliothèque municipale (Organisation)',
       'Blois, Musée des Beaux-Arts (Organisation)',
       "Blois, Musée diocésain d'Art religieux (Organisation)",
       'Bordeaux, Bibliothèque municipale (Organisation)',
       'Boulogne-sur-Mer, Bibliothèque municipale (Organisation)',
       'Caen, Musée des Beaux-Arts (Organisation)',
       'Calais, Bibliothèque municipale (Organisation)',
       'Chambéry, Bibliothèque municipale (Organisation)',
       'Chambéry, Musée savoisien (Organisation)',
       'Chantilly, Bibliothèque et archives du musée Condé (Organisation)',
       'Chartres, Bibliothèque municipale (Organisation)',
       'Château-Gontier, Bibliothèque municipale (Organisation)',
       'Chaumont, Bibliothèque municipale (Organisation)',
       'Coutances, Bibliothèque municipale (Organisation)',
       'Dieppe, Château-Musée (Organisation)',
       'Dijon, Bibliothèque municipale (Organisation)',
       'Douai, Bibliothèque municipale (Organisation)',
       'Fécamp, Musée du Palais Bénédictine (Organisation)',
       'Langres, Bibliothèque municipale (Organisation)',
       'Le Mans, Bibliothèque municipale (Organisation)',
       'Le Puy-en-Velay, Bibliothèque diocésaine (Organisation)',
       'Le Puy-en-Velay, Bibliothèque municipale (Organisation)',
       'Lyon, Bibliothèque municipale (Organisation)',
       'Mâcon, Bibliothèque municipale (Organisation)',
       'Melun, Bibliothèque municipale (Organisation)',
       "Melun, Musée d'Art et d'Histoire (Organisation)",
       'Metz, Bibliothèque municipale (Organisation)',
       "Montbrison, Musée d'Allard (Organisation)",
       'Nantes, Bibliothèque municipale (Organisation)',
       'Nantes, Musée Dobrée (Organisation)',
       'Nîmes, Bibliothèque municipale (Organisation)',
       'Paris, Bibliothèque du Centre culturel irlandais (Organisation)',
       'Paris, Bibliothèque du Saulchoir (Organisation)',
       'Paris, Bibliothèque Mazarine (Organisation)',
       "Paris, Bibliothèque nationale de France, Bibliothèque de l'Arsenal (Organisation)",
       'Paris, Bibliothèque nationale de France, Manuscrits (Organisation)',
       'Paris, Bibliothèque Sainte-Geneviève (Organisation)',
       'Aubervilliers, IRHT, Collections privées (Organisation)',
       'Paris, Musée des Arts décoratifs (Organisation)',
       'Paris, Musée Jacquemart-André (Organisation)',
       'Paris, Petit Palais, Musée des Beaux-Arts de la ville de Paris (Organisation)',
       'Poitiers, Bibliothèque municipale (Organisation)',
       'Provins, Bibliothèque municipale (Organisation)',
       'Reims, Bibliothèque municipale (Organisation)',
       'Rennes, Bibliothèque municipale (Organisation)',
       "Rodez, Bibliothèque de la Société des lettres de l'Aveyron (Organisation)",
       'Rodez, Bibliothèque municipale (Organisation)',
       'Rouen, Bibliothèque municipale (Organisation)',
       'Rouen, Musée des Beaux-Arts (Organisation)',
       "Saint-Omer, Bibliothèque d'agglomération (Organisation)",
       'Saumur, Château-Musée (Organisation)',
       'Sées, Archives diocésaines (Organisation)',
       'Sens, Bibliothèque municipale (Organisation)',
       'Soissons, Bibliothèque municipale (Organisation)',
       "Solesmes, Bibliothèque de l'abbaye Saint-Pierre (Organisation)",
       'Strasbourg, Bibliothèque du Grand Séminaire (Organisation)',
       'Tonnerre, Bibliothèque municipale (Organisation)',
       'Toulouse, Bibliothèque municipale (Organisation)',
       'Toulouse, Musée Saint-Raymond (Organisation)',
       'Tournus, Hôtel-Dieu - Musée Greuze (Organisation)',
       'Tours, Bibliothèque municipale (Organisation)',
       'Versailles, Bibliothèque municipale (Organisation)',
       'Cambridge, Corpus Christi College (Organisation)',
       'Cambridge, Trinity College (Organisation)',
       'Cambridge, University Library (Organisation)',
       'Oxford, Bodleian Library (Organisation)',
       'Oxford, Christ Church (Organisation)',
       'Napoli, Biblioteca Nazionale Vittorio Emanuele III (Organisation)',
       'Torino, Biblioteca Reale (Organisation)',
       "'s-Gravenhage, Koninklijke Bibliotheek (Organisation)",
       'Kraków, Muzeum Narodowe, Biblioteka Czartoryskich (Organisation)',
       'Warszawa, Biblioteka Narodowa (Organisation)',
       'Baltimore, The Walters Art Museum (Organisation)',
       'Cambridge (MA), Harvard University, Houghton Library (Organisation)',
       "Collegeville (Minn), Saint John's University. Hill Museum & Manuscript Library. Special Collections (Organisation)",
       'Los Angeles, University of California Los Angeles Library, Department of Special Collections (Organisation)',
       'New Haven, Yale University Library, Beinecke Rare Book and Manuscript Library (Organisation)',
       'Philadelphia, Free Library of Philadelphia (Organisation)',
       'Philadelphia, Library Company (Organisation)',
       'Philadelphia, Philadelphia Museum of Art, Department of Prints, Drawings, and Photographs (Organisation)',
       'Philadelphia, University of Pennsylvania, Kislak Center for Special Collections, Rare Books and Manuscripts (Organisation)',
       'San Marino, Huntington Library (Organisation)',
       'Saint Benedict (Oregon), Mount Angel Abbey Library (Organisation)',
       'Washington (DC), Library of Congress (Organisation)',
       'Vaticano, Biblioteca Apostolica Vaticana (Organisation)',
       'Saint-Denis, Bibliothèque municipale (Organisation)',
       'Wrocław, Biblioteka Uniwersytecka we Wrocławiu (Organisation)',
       'St. Gallen, Kantonsbibliothek, Vadianische Sammlung (Organisation)',
       'Martin, Slovenská národná knižnica (Organisation)',
       "Collegeville (Minn), Saint John's University Library, Rare Book Collection (Organisation)",
       "Collegeville (Minn), Saint John's University. Arca Artium Rare Book Collection (Organisation)",
       'Philadelphia, Temple University Library, Special Collections Research Center (Organisation)',
       'Bryn Mawr, Bryn Mawr College Library (Organisation)',
       'Newark, University of Delaware Library (Organisation)',
       'Philadelphia, Free Library of Philadelphia, The Rosenbach (Organisation)',
       'Philadelphia, University of Pennsylvania, Library at the Herbert D. Katz Center for Advanced Judaic Studies (Organisation)',
       'Bethlehem, Lehigh University Libraries, Special Collections (Organisation)',
       'New York, Fordham University, Walsh Library, Archives and Special Collections (Organisation)',
       'Aubervilliers, IRHT, Manuscrits (Organisation)',
       'Heidelberg, Universitätsbibliothek (Organisation)',
       'Angers, Archives départementales de Maine-et-Loire (Organisation)',
       '[current whereabouts unknown] (Organisation)',
       'Minneapolis, University of Minnesota Libraries, Special Collections and Rare Books (Organisation)',
       'Brno, Moravská galerie Brno (Organisation)',
       'Praha, Národní knihovna České republiky (Organisation)',
       'Alba Iulia, Biblioteca Naţională a României-Filiala Batthyaneum (Organisation)',
       'Toruń, Biblioteka Uniwersytecka w Toruń (Organisation)',
       'Vyšší Brod, Klášterní Knihovna (Organisation)',
       'Plzeň, Knihovna Západočeského muzea v Plzni (Organisation)',
       'Brno, Moravská zemská knihovna v Brně (Organisation)'],
      dtype=object)

In [35]:
df['repository_key (Organisation) Record Title'].unique()

array(['nnbkc,uIsr ihtnvkitisirsUeätboble gin(istraaOo)n',
       'g,rgBue neaOprbe Bkhtieleiob gBuger i()rfBeko Ooaiarsinn)(tg',
       'rgBegu, banerOep hkibeiolBet rgBeug feB(ori)k s)aOtga(ionirn',
       ..., 'Pr,aah nádíNor knonhvai Čskée ylurbpkie O(gtnsroi)aani',
       'Hlirb,edeeg sheorättebitnikiUisvbl ng(iisr)antOao',
       'aa,Phr nnovhKai oNonídhár meuza ragoi)a(Oitnns'], dtype=object)

In [44]:
%%time 

df = mss.copy(deep=True)

# Columns to add noise
columns_with_noise = ['repository_key (Organisation) Record Title']

# Function to introduce spelling mistakes in a word
def introduce_spelling_mistake(word):
    # Randomly choose a mistake operation (e.g., replacing character, adding or removing character)
    mistake_operation = random.choice(['replace', 'add', 'remove'])

    if mistake_operation == 'replace':
        # Replace a character with a similar-looking character
        letters = list(word)
        index = random.randint(0, len(letters) - 1)
        letters[index] = random.choice(list(letters[index]))
        return ''.join(letters)
    elif mistake_operation == 'add':
        # Add a random character after a randomly chosen position
        letters = list(word)
        index = random.randint(0, len(letters))
        letters.insert(index, random.choice(list('abcdefghijklmnopqrstuvwxyz')))
        return ''.join(letters)
    elif mistake_operation == 'remove':
        # Remove a character at a randomly chosen position
        letters = list(word)
        index = random.randint(0, len(letters) - 1)
        del letters[index]
        return ''.join(letters)
    else:
        return word

# Add noise to selected columns
for column in columns_with_noise:
    # Iterate over each row in the column
    for i in range(len(df)):
        # Split the text into individual words
        words = df.loc[i, column].split()
        
        # Add noise to each word
        noisy_words = []
        for word in words:
            # Apply spelling mistake only if the word has more than two characters
            if len(word) > 2:
                # Randomly choose whether to introduce a spelling mistake or not
                introduce_mistake = random.random() < 0.5  # Adjust the probability as per your requirement
                
                if introduce_mistake:
                    # Introduce a spelling mistake
                    noisy_word = introduce_spelling_mistake(word)
                    noisy_words.append(noisy_word)
                else:
                    noisy_words.append(word)
            else:
                noisy_words.append(word)
        
        # Join the noisy words back into a sentence
        noisy_text = ' '.join(noisy_words)
        
        # Update the DataFrame with the noisy text

Wall time: 121 ms

In [42]:
len(df['repository_key (Organisation) Record Title'].unique())

158

In [43]:
len(mss['repository_key (Organisation) Record Title'].unique())

158