# Beten nach Daten: statistiche Übersichten betr. Datum, Format und Entstehungsort

<a href="https://colab.research.google.com/github/oriflamms/LivreQuanti2023/blob/main/DataModelling/Zeit-Raum-Dimensionen-Deutschland.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Environment

In [1]:
import os, pandas as pd, numpy as np
from urllib.request import urlopen

from scipy.stats import chi2_contingency
print(os.getcwd())
# Set the maximum number of rows and columns to display
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

C:\Users\stutzmann\Github\LivreQuanti2023\DataModelling

# Data (capta)

## Load data

Only if on Google Colab. Skip if used locally

In [2]:
file_url_1 = 'https://raw.githubusercontent.com/oriflamms/LivreQuanti2023/main/DataModelling/Export_stutzmann_horae_t53_Manuscript_rich_20231109.xlsx'
file_url_2 = 'https://raw.githubusercontent.com/oriflamms/LivreQuanti2023/main/DataModelling/t53_Manuscript_Country.csv'
!wget {file_url_1}
!wget {file_url_2}

'wget' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.
'wget' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.

Back to main track if repo is cloned and used locally

In [3]:
#df = pd.read_excel('./Export_stutzmann_horae_t53_numformat.xlsx', sheet_name='Capta')
df = pd.read_excel('./Export_stutzmann_horae_t53_Manuscript_rich_20231109.xlsx', sheet_name='Tabelle2')
df_country = pd.read_csv('./t53_Manuscript_Country.csv', sep=';')

## Check contents

In [4]:
print(df.shape)
print(list(df.columns))
df.head()

(8916, 33)
['Manuscript H-ID', 'repository_key (Organisation) H-ID', 'repository_key (Organisation) Record Title', 'idno', 'altIdentifier', 'idMedium', 'msItem H-ID', 'rec_Title_2', 'Work H-ID', 'Work Record Title', 'number of volume', 'support', 'extent', 'leaf dimensions : height (mm)', 'leaf dimensions : width (mm)', 'justification : height (mm)', 'justification : width (mm)', 'columns', 'writtenLines', 'script type', 'formality', 'origDate', 'origDate : from', 'origDate : to', 'origDate : proposed date', 'origPlace (relationship marker) H-ID', 'origPlace (relationship marker) Record Title', 'origPlace : proposed origin', 'iiif manifest', 'bibl H-ID', 'bibl Record Title', 'external link (Web site / page) H-ID', 'external link (Web site / page) Record Title']

,Manuscript H-ID,repository_key (Organisation) H-ID,repository_key (Organisation) Record Title,idno,altIdentifier,idMedium,msItem H-ID,rec_Title_2,Work H-ID,Work Record Title,number of volume,support,extent,leaf dimensions : height (mm),leaf dimensions : width (mm),justification : height (mm),justification : width (mm),columns,writtenLines,script type,formality,origDate,origDate : from,origDate : to,origDate : proposed date,origPlace (relationship marker) H-ID,origPlace (relationship marker) Record Title,origPlace : proposed origin,iiif manifest,bibl H-ID,bibl Record Title,external link (Web site / page) H-ID,external link (Web site / page) Record Title
0,433,739889,"Montréal, McGill University Library (Organisat...",101,NaN,100086833.0,737250,"Montréal, McGill University Library, 101 : Hou...",75966,Hours of the Virgin | L1 | Section,NaN,parchment,053 ff. (CCLL)|53 ff.,NaN,NaN,98,60,1.0,NaN,NaN,NaN,NaN,1470|1450,1470|1480,NaN,37509,Brugge (Place),Bruges,NaN,352571|737330,"De Ricci et Wilson 1935-1937, II, p. 2212|Dunn...",325568,"McGill Digital Library, http://digital.library..."
1,734419,740297,"Maastricht, Regionaal Historisch Centrum Limbu...",ms. 48,NaN,NaN,735336,"Maastricht, Regionaal Historisch Centrum Limbu...",75966,Hours of the Virgin | L1 | Section,NaN,parchment,105 ff. (paginated: 1-204),177,131,101,70,1.0,17.0,Textualis,NaN,NaN,1451,1475,third quarter 15th century,37669,Hainaut (Place),NaN,NaN,736662|736663,"Wouters 1962, no. 95|Cat. Monnikenwerk, no. 30",735403,"MMDC, http://www.mmdc.nl/static/site/search/de..."
2,6513,740138,"Cambridge (MA), Harvard University, Houghton L...",MS Typ 0464,NaN,NaN,715768,"Cambridge (MA), Harvard University, Houghton L...",75966,Hours of the Virgin | L1 | Section,NaN,parchment,147 ff. (CCLL)|ff. 147,116,88,64,45,1.0,NaN,Cursiva,NaN,NaN,1480,1500,c. 1475-80,38142,Bourges (Place),"Bourges, France",https://iiif.lib.harvard.edu/manifests/drs:497...,354463|351329|741031|741991|742134,"1983, Cambridge (Mass), p. 34 n° 16, fig.|Bond...",741340,"Digital Scriptorium, http://ds.lib.berkeley.ed..."
3,6494,740138,"Cambridge (MA), Harvard University, Houghton L...",MS Typ 1000,NaN,NaN,715765,"Cambridge (MA), Harvard University, Houghton L...",75966,Hours of the Virgin | L1 | Section,NaN,parchment,"ff.162 ( numbered ff. 171, lacking ff. 144, 14...",83,57,54,36,NaN,NaN,Humanistique,NaN,NaN,1501,1550,c. 1500-10,38068,Venezia (Place),"Venice, Italy",https://iiif.lib.harvard.edu/manifests/drs:103...,741003|742210,"Boston 2016, p. 294 n° 234|Mariani Canova 1975",741328,"Digital Scriptorium, http://ds.lib.berkeley.ed..."
4,6456,740138,"Cambridge (MA), Harvard University, Houghton L...",MS Lat 017,NaN,NaN,715762,"Cambridge (MA), Harvard University, Houghton L...",75966,Hours of the Virgin | L1 | Section,NaN,parchment,141 ff. (CCLL),200,132,NaN,NaN,1.0,NaN,Hybrida,NaN,NaN,1476,1500,NaN,37638,France (Place),NaN,https://iiif.lib.harvard.edu/manifests/drs:108...,356441|357556|349972|742148|742106|742300,"Light 1995, p. 23-29, pl. 31|1983, Cambridge (...",741221,"Digital Scriptorium, http://ds.lib.berkeley.ed..."

In [5]:
df_country.head()

,Manuscript H-ID,rec_Title,origPlace (relationship marker) H-ID,Country
0,1,"Admont, Stiftsbibliothek, 876b",NaN,NaN
1,2,"Göttweig, Stiftsbibliothek, 450 (235)",NaN,NaN
2,3,"Göttweig, Stiftsbibliothek, 452 (237)",NaN,NaN
3,4,"Göttweig, Stiftsbibliothek, 453 (238)",NaN,NaN
4,5,"Göttweig, Stiftsbibliothek, Sn 1",NaN,NaN

## Merge dataframes based on "Manuscript H-ID" to add "Country" to main

In [6]:
df = pd.merge(df, df_country[['Manuscript H-ID', 'Country']], on='Manuscript H-ID', how='left')
df.shape

(8916, 34)

In [7]:
df.head()

,Manuscript H-ID,repository_key (Organisation) H-ID,repository_key (Organisation) Record Title,idno,altIdentifier,idMedium,msItem H-ID,rec_Title_2,Work H-ID,Work Record Title,number of volume,support,extent,leaf dimensions : height (mm),leaf dimensions : width (mm),justification : height (mm),justification : width (mm),columns,writtenLines,script type,formality,origDate,origDate : from,origDate : to,origDate : proposed date,origPlace (relationship marker) H-ID,origPlace (relationship marker) Record Title,origPlace : proposed origin,iiif manifest,bibl H-ID,bibl Record Title,external link (Web site / page) H-ID,external link (Web site / page) Record Title,Country
0,433,739889,"Montréal, McGill University Library (Organisat...",101,NaN,100086833.0,737250,"Montréal, McGill University Library, 101 : Hou...",75966,Hours of the Virgin | L1 | Section,NaN,parchment,053 ff. (CCLL)|53 ff.,NaN,NaN,98,60,1.0,NaN,NaN,NaN,NaN,1470|1450,1470|1480,NaN,37509,Brugge (Place),Bruges,NaN,352571|737330,"De Ricci et Wilson 1935-1937, II, p. 2212|Dunn...",325568,"McGill Digital Library, http://digital.library...",Belgium
1,734419,740297,"Maastricht, Regionaal Historisch Centrum Limbu...",ms. 48,NaN,NaN,735336,"Maastricht, Regionaal Historisch Centrum Limbu...",75966,Hours of the Virgin | L1 | Section,NaN,parchment,105 ff. (paginated: 1-204),177,131,101,70,1.0,17.0,Textualis,NaN,NaN,1451,1475,third quarter 15th century,37669,Hainaut (Place),NaN,NaN,736662|736663,"Wouters 1962, no. 95|Cat. Monnikenwerk, no. 30",735403,"MMDC, http://www.mmdc.nl/static/site/search/de...",Belgium
2,6513,740138,"Cambridge (MA), Harvard University, Houghton L...",MS Typ 0464,NaN,NaN,715768,"Cambridge (MA), Harvard University, Houghton L...",75966,Hours of the Virgin | L1 | Section,NaN,parchment,147 ff. (CCLL)|ff. 147,116,88,64,45,1.0,NaN,Cursiva,NaN,NaN,1480,1500,c. 1475-80,38142,Bourges (Place),"Bourges, France",https://iiif.lib.harvard.edu/manifests/drs:497...,354463|351329|741031|741991|742134,"1983, Cambridge (Mass), p. 34 n° 16, fig.|Bond...",741340,"Digital Scriptorium, http://ds.lib.berkeley.ed...",France
3,6494,740138,"Cambridge (MA), Harvard University, Houghton L...",MS Typ 1000,NaN,NaN,715765,"Cambridge (MA), Harvard University, Houghton L...",75966,Hours of the Virgin | L1 | Section,NaN,parchment,"ff.162 ( numbered ff. 171, lacking ff. 144, 14...",83,57,54,36,NaN,NaN,Humanistique,NaN,NaN,1501,1550,c. 1500-10,38068,Venezia (Place),"Venice, Italy",https://iiif.lib.harvard.edu/manifests/drs:103...,741003|742210,"Boston 2016, p. 294 n° 234|Mariani Canova 1975",741328,"Digital Scriptorium, http://ds.lib.berkeley.ed...",Italy
4,6456,740138,"Cambridge (MA), Harvard University, Houghton L...",MS Lat 017,NaN,NaN,715762,"Cambridge (MA), Harvard University, Houghton L...",75966,Hours of the Virgin | L1 | Section,NaN,parchment,141 ff. (CCLL),200,132,NaN,NaN,1.0,NaN,Hybrida,NaN,NaN,1476,1500,NaN,37638,France (Place),NaN,https://iiif.lib.harvard.edu/manifests/drs:108...,356441|357556|349972|742148|742106|742300,"Light 1995, p. 23-29, pl. 31|1983, Cambridge (...",741221,"Digital Scriptorium, http://ds.lib.berkeley.ed...",France

## Data types: check to allow for subsequent manipulation

In [8]:
print(df['leaf dimensions : height (mm)'].dtypes)
# print(df['leaf dimensions : height (mm)'].unique())
print(df['origDate'].dtypes)
# print(df['origDate'].unique())
print(df['origDate : from'].dtypes)
# print(df['origDate : from'].unique())
print(df['origDate : to'].dtypes)
# print(df['origDate : to'].unique())
print(df['Country'].dtypes)
# print(sorted(df['Country'].unique()))

object
object
object
object
object

In [9]:
df['leaf dimensions : height (mm)'] = pd.to_numeric(df['leaf dimensions : height (mm)'], errors='coerce')
df['leaf dimensions : width (mm)'] = pd.to_numeric(df['leaf dimensions : width (mm)'], errors='coerce')
df['origDate'] = pd.to_numeric(df['origDate'], errors='coerce')
df['origDate : from'] = pd.to_numeric(df['origDate : from'], errors='coerce')
df['origDate : to'] = pd.to_numeric(df['origDate : to'], errors='coerce')
df['Country'] = df['Country'].astype(str)

# Data manipulation

## Calculate "average" dates for manuscripts with precise dates and with dating intervals

In [10]:
# Define a function to calculate the "origDate-avg"
def calculate_origDate_avg(row):
    if not pd.isna(row['origDate']):
        return row['origDate']
    elif not pd.isna(row['origDate : from']) and not pd.isna(row['origDate : to']):
        return (row['origDate : from'] + row['origDate : to']) / 2
    else:
        return np.nan

# Apply the function to create the new column
df['origDate-avg'] = df.apply(calculate_origDate_avg, axis=1)
# df['origDate-avg'] = df['origDate-avg'].round().astype(int)

In [11]:
df.head()

,Manuscript H-ID,repository_key (Organisation) H-ID,repository_key (Organisation) Record Title,idno,altIdentifier,idMedium,msItem H-ID,rec_Title_2,Work H-ID,Work Record Title,number of volume,support,extent,leaf dimensions : height (mm),leaf dimensions : width (mm),justification : height (mm),justification : width (mm),columns,writtenLines,script type,formality,origDate,origDate : from,origDate : to,origDate : proposed date,origPlace (relationship marker) H-ID,origPlace (relationship marker) Record Title,origPlace : proposed origin,iiif manifest,bibl H-ID,bibl Record Title,external link (Web site / page) H-ID,external link (Web site / page) Record Title,Country,origDate-avg
0,433,739889,"Montréal, McGill University Library (Organisat...",101,NaN,100086833.0,737250,"Montréal, McGill University Library, 101 : Hou...",75966,Hours of the Virgin | L1 | Section,NaN,parchment,053 ff. (CCLL)|53 ff.,NaN,NaN,98,60,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37509,Brugge (Place),Bruges,NaN,352571|737330,"De Ricci et Wilson 1935-1937, II, p. 2212|Dunn...",325568,"McGill Digital Library, http://digital.library...",Belgium,NaN
1,734419,740297,"Maastricht, Regionaal Historisch Centrum Limbu...",ms. 48,NaN,NaN,735336,"Maastricht, Regionaal Historisch Centrum Limbu...",75966,Hours of the Virgin | L1 | Section,NaN,parchment,105 ff. (paginated: 1-204),177.0,131.0,101,70,1.0,17.0,Textualis,NaN,NaN,1451.0,1475.0,third quarter 15th century,37669,Hainaut (Place),NaN,NaN,736662|736663,"Wouters 1962, no. 95|Cat. Monnikenwerk, no. 30",735403,"MMDC, http://www.mmdc.nl/static/site/search/de...",Belgium,1463.0
2,6513,740138,"Cambridge (MA), Harvard University, Houghton L...",MS Typ 0464,NaN,NaN,715768,"Cambridge (MA), Harvard University, Houghton L...",75966,Hours of the Virgin | L1 | Section,NaN,parchment,147 ff. (CCLL)|ff. 147,116.0,88.0,64,45,1.0,NaN,Cursiva,NaN,NaN,1480.0,1500.0,c. 1475-80,38142,Bourges (Place),"Bourges, France",https://iiif.lib.harvard.edu/manifests/drs:497...,354463|351329|741031|741991|742134,"1983, Cambridge (Mass), p. 34 n° 16, fig.|Bond...",741340,"Digital Scriptorium, http://ds.lib.berkeley.ed...",France,1490.0
3,6494,740138,"Cambridge (MA), Harvard University, Houghton L...",MS Typ 1000,NaN,NaN,715765,"Cambridge (MA), Harvard University, Houghton L...",75966,Hours of the Virgin | L1 | Section,NaN,parchment,"ff.162 ( numbered ff. 171, lacking ff. 144, 14...",83.0,57.0,54,36,NaN,NaN,Humanistique,NaN,NaN,1501.0,1550.0,c. 1500-10,38068,Venezia (Place),"Venice, Italy",https://iiif.lib.harvard.edu/manifests/drs:103...,741003|742210,"Boston 2016, p. 294 n° 234|Mariani Canova 1975",741328,"Digital Scriptorium, http://ds.lib.berkeley.ed...",Italy,1525.5
4,6456,740138,"Cambridge (MA), Harvard University, Houghton L...",MS Lat 017,NaN,NaN,715762,"Cambridge (MA), Harvard University, Houghton L...",75966,Hours of the Virgin | L1 | Section,NaN,parchment,141 ff. (CCLL),200.0,132.0,NaN,NaN,1.0,NaN,Hybrida,NaN,NaN,1476.0,1500.0,NaN,37638,France (Place),NaN,https://iiif.lib.harvard.edu/manifests/drs:108...,356441|357556|349972|742148|742106|742300,"Light 1995, p. 23-29, pl. 31|1983, Cambridge (...",741221,"Digital Scriptorium, http://ds.lib.berkeley.ed...",France,1488.0

## Limit data set to manuscripts with numeric dimensions

Drop rows with NaN, 0, or blank values, or for values less than 35 mm, which are typically fragments and cuttings which are not apt to represent the original manuscripts

In [12]:

df = df.dropna(subset=['leaf dimensions : height (mm)'])
df = df.dropna(subset=['leaf dimensions : width (mm)'])
df = df[df['leaf dimensions : height (mm)'] > 35]
df = df[df['leaf dimensions : width (mm)'] > 35]
df.shape

(6482, 35)

## Clean informations on countries

Because the geographic origin is sometimes indicated in a list of several hypotheses, the "Country" information is repeated, be it the duplicaton of the same information (e.g. "France|France") or with conflicting informations (e.g. "Germany|Austria).

The following function reduces the duplicated and identical values to a single string and converts conflicting hypotheses to the information "multiple countries"

In [13]:
def process_country(value):
    countries = [country.strip() for country in value.split('|') if country.strip()]
    
    # Check if all values are the same
    if len(set(countries)) == 1:
        return countries[0]
    else:
        # If multiple values, return sorted and unique values
        # return '|'.join(sorted(set(countries)))
        return 'multiple countries'

# Apply the function to create the new "Processed_Country" column
df['Processed_Country'] = df['Country'].apply(process_country)

## Dimensions by DateRange (span of 50 years)

Instead of the manual grouping in Excel, the following code automates the creation of date categories by date range with an interval. The interval here is a suggested interval of 50 years.

In [14]:
interval = 50

In [15]:
# Convert 'origDate-avg' to numeric, coercing errors to NaN
df['origDate-avg'] = pd.to_numeric(df['origDate-avg'], errors='coerce')

# Create a new column for the date range categories
bins = range(1001, 2001, interval)
labels = [f"{start}-{start+interval-1}" for start in bins[:-1]]
df['DateRange'] = pd.cut(df['origDate-avg'], bins=bins, labels=labels, right=False)

# Categories and pivot tables

## Dimensions by country

In [16]:
pivot_table_dimensions = df.pivot_table(
    values=['leaf dimensions : height (mm)', 'leaf dimensions : width (mm)', 'Manuscript H-ID'],
    index='Processed_Country',
    aggfunc={
        'leaf dimensions : height (mm)': 'mean',
        'leaf dimensions : width (mm)': 'mean',
        'Manuscript H-ID': 'count'
    }
).round(1)

# Calculate the additional column for 'average of height x width'
pivot_table_dimensions['average of height x width (cm²)'] = (
    pivot_table_dimensions['leaf dimensions : height (mm)'] * 
    pivot_table_dimensions['leaf dimensions : width (mm)'] / 100
).round(1)

# Rename the columns for clarity
pivot_table_dimensions = pivot_table_dimensions.rename(columns={
    'leaf dimensions : height (mm)': 'average height (mm)',
    'leaf dimensions : width (mm)': 'average width (mm)',
    'Manuscript H-ID': 'count Manuscript H-ID'
})

# Display the pivot table
pivot_table_dimensions

,count Manuscript H-ID,average height (mm),average width (mm),average of height x width (cm²)
Processed_Country,,,,
Austria,4,130.2,95.0,123.7
Belgium,476,162.0,116.8,189.2
Czech Republic,8,161.2,114.5,184.6
France,1854,173.5,122.1,211.8
Germany,74,128.3,94.0,120.6
Italy,340,133.4,95.8,127.8
Lithuania,5,150.0,112.0,168.0
Netherlands,700,156.1,110.5,172.5
Poland,2,109.5,88.0,96.4
Portugal,2,120.0,93.0,111.6
Romania,1,160.0,115.0,184.0
Spain,5,158.0,124.2,196.2
Sweden,5,145.4,103.0,149.8
Switzerland,7,172.4,120.6,207.9
UK,57,175.2,126.8,222.2
multiple countries,185,172.0,121.5,209.0
nan,2757,162.0,114.0,184.7

## Dimensions by date range

In [17]:
pivot_table_dimensions_by_DateRange  = df.pivot_table(
    values=['leaf dimensions : height (mm)', 'leaf dimensions : width (mm)', 'Manuscript H-ID'],
    index='DateRange',
    aggfunc={
        'leaf dimensions : height (mm)': 'mean',
        'leaf dimensions : width (mm)': 'mean',
        'Manuscript H-ID': 'count'
    }
).round(1)

# Calculate the additional column for 'average of height x width'
pivot_table_dimensions_by_DateRange['average of height x width (cm²)'] = (
    pivot_table_dimensions_by_DateRange['leaf dimensions : height (mm)'] * 
    pivot_table_dimensions_by_DateRange['leaf dimensions : width (mm)'] / 100
).round(1)

# Rename the columns for clarity
pivot_table_dimensions_by_DateRange = pivot_table_dimensions_by_DateRange.rename(columns={
    'leaf dimensions : height (mm)': 'average height (mm)',
    'leaf dimensions : width (mm)': 'average width (mm)',
    'Manuscript H-ID': 'count Manuscript H-ID'
})

# Display the pivot table
pivot_table_dimensions_by_DateRange

,count Manuscript H-ID,average height (mm),average width (mm),average of height x width (cm²)
DateRange,,,,
1001-1050,0,NaN,NaN,NaN
1051-1100,0,NaN,NaN,NaN
1101-1150,2,167.5,119.0,199.3
1151-1200,9,223.1,153.4,342.2
1201-1250,36,195.9,137.5,269.4
1251-1300,69,176.6,126.2,222.9
1301-1350,153,156.3,110.4,172.6
1351-1400,215,160.1,113.9,182.4
1401-1450,2231,165.3,118.3,195.5
1451-1500,2846,161.2,113.7,183.3
1501-1550,700,161.9,110.4,178.7
1551-1600,36,177.5,121.9,216.4
1601-1650,15,150.1,102.9,154.5
1651-1700,3,236.0,168.3,397.2
1701-1750,1,129.0,80.0,103.2
1751-1800,0,NaN,NaN,NaN
1801-1850,5,124.6,129.6,161.5
1851-1900,0,NaN,NaN,NaN
1901-1950,1,193.0,142.0,274.1

## Dimensions by Date Range and Countries

In [18]:
# Pivot table for average dimensions by DateRange and Country
pivot_table_avg_dimensions = df.pivot_table(
    values='leaf dimensions : height (mm)',
    index=['DateRange', 'Processed_Country'],
    aggfunc='mean',
    margins=True,  # Add subtotals
    margins_name='missing',  # Specify the name for the subtotal row
).round(1)

In [19]:
pivot_table_avg_dimensions

                              leaf dimensions : height (mm)
DateRange Processed_Country
1101-1150 France                                      175.0
          Germany                                     160.0
1151-1200 France                                      228.0
          Germany                                     189.0
          nan                                         227.3
1201-1250 Belgium                                     180.2
          France                                      195.0
          Germany                                     250.0
          UK                                          227.2
          multiple countries                          167.0
          nan                                         189.2
1251-1300 Belgium                                     159.2
          France                                      207.4
          Germany                                     119.0
          Italy                                       124.3
          Netherlands                                 167.5
          Switzerland                                 335.0
          UK                                          158.0
          multiple countries                          186.0
          nan                                         171.2
1301-1350 Belgium                                     138.0
          Czech Republic                              245.0
          France                                      154.8
          Germany                                     117.5
          Italy                                       149.0
          Netherlands                                 149.0
          UK                                          219.5
          nan                                         155.9
1351-1400 Austria                                     141.0
          Belgium                                     139.7
          France                                      162.1
          Germany                                     122.0
          Italy                                       156.4
          Netherlands                                 161.2
          UK                                          195.9
          multiple countries                          172.5
          nan                                         158.2
1401-1450 Austria                                     140.0
          Belgium                                     167.3
          Czech Republic                              127.5
          France                                      175.5
          Germany                                     128.7
          Italy                                       123.8
          Lithuania                                   140.0
          Netherlands                                 149.0
          Sweden                                      135.0
          Switzerland                                 100.0
          UK                                          157.3
          multiple countries                          181.8
          nan                                         165.3
1451-1500 Austria                                     120.0
          Belgium                                     160.2
          Czech Republic                              180.0
          France                                      171.3
          Germany                                     117.1
          Italy                                       132.7
          Lithuania                                   152.5
          Netherlands                                 159.7
          Poland                                       86.0
          Spain                                       153.8
          Sweden                                      175.0
          Switzerland                                 166.8
          UK                                          210.7
          multiple countries                          163.4
          nan                                         159.6
1501-1550 Belgium                                     161.3
          Czech Republic                              130.0
          France                                      175.6
          Germany                                     122.8
          Italy                                       151.7
          Netherlands                                 146.7
          Poland                                      133.0
          Portugal                                    142.0
          Romania                                     160.0
          Sweden                                      141.0
          Switzerland                                 105.0
          multiple countries                          178.3
          nan                                         159.0
1551-1600 Belgium                                     142.7
          France                                      198.0
          Italy                                        95.5
          nan                                         183.9
1601-1650 France                                      164.0
          Germany                                     117.5
          Italy                                       207.7
          Spain                                       175.0
          nan                                         131.8
1651-1700 France                                      297.0
          nan                                         205.5
1701-1750 nan                                         129.0
1801-1850 UK                                          105.0
          nan                                         137.7
1901-1950 nan                                         193.0
missing                                               163.1

In [20]:
# Pivot table for average dimensions by DateRange and Country
pivot_table_avg_dimensions_full = df.pivot_table(
    values=['leaf dimensions : height (mm)', 'Manuscript H-ID'],
    index=['DateRange', 'Processed_Country'],
    aggfunc={'leaf dimensions : height (mm)': 'mean', 'Manuscript H-ID': 'count'},
    margins=True,  # Add subtotals
    margins_name='missing',  # Specify the name for the subtotal row
).round(1)

pivot_table_avg_dimensions_full.head()

                             Manuscript H-ID  leaf dimensions : height (mm)
DateRange Processed_Country
1001-1050 Austria                          0                            NaN
          Belgium                          0                            NaN
          Czech Republic                   0                            NaN
          France                           0                            NaN
          Germany                          0                            NaN

# Correlation (khi2)

## Date and Country

In [21]:
# Create a contingency table
contingency_table = pd.crosstab(df['Processed_Country'], df['DateRange'])

# Perform the chi-squared test
chi2, p, _, _ = chi2_contingency(contingency_table)

# Print the results
print("Correlation between country and time intervals")
print(f"Chi-squared value: {chi2}")
print(f"P-value: {p}")

Correlation between country and time intervals
Chi-squared value: 717.2346008399434
P-value: 5.399900103085132e-53

## Size and Date

In [22]:
# Create a new column for the date range categories
bins = range(0, 900, 20)
labels = [f"{start}-{start+19}" for start in bins[:-1]]
df['heightRange'] = pd.cut(df['leaf dimensions : height (mm)'], bins=bins, labels=labels, right=False)


# Create a contingency table
contingency_table = pd.crosstab(df['heightRange'], df['DateRange'])

# Perform the chi-squared test
chi2, p, _, _ = chi2_contingency(contingency_table)

# Print the results
print("Correlation between size and time intervals")
print(f"Chi-squared value: {chi2}")
print(f"P-value: {p}")

Correlation between size and time intervals
Chi-squared value: 879.9334544663138
P-value: 2.5421570446983096e-50

## Country and Size

In [23]:
# Create a contingency table
contingency_table = pd.crosstab(df['heightRange'], df['Country'])

# Perform the chi-squared test
chi2, p, _, _ = chi2_contingency(contingency_table)

# Print the results
print("Correlation between size and countries")
print(f"Chi-squared value: {chi2}")
print(f"P-value: {p}")

Correlation between size and countries
Chi-squared value: 1724.194832152751
P-value: 2.5318515628186418e-06